apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  selector:
    matchLabels:
      app: auth
  replicas: 2
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: juanballesteros/auth_distri:latest
        imagePullPolicy: Always
        env:
          - name: JWT_SECRET
            value: "PRFT" 
          - name: AUTH_API_PORT
            value: "8000" 
          - name: USERS_API_ADDRESS
            value: http://$(DISTRI_USERS_SERVICE_HOST):8083
        ports:
            - containerPort: 8000
        resources:
          limits:
              memory: 512Mi
              cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"