apiVersion: v1
kind: Service
metadata:
  name: todos-service-p2
  labels:
    app: todos
spec:
  type: LoadBalancer
  selector:
   project: p2
   service: parcial2
  ports:
   - protocol: TCP
     port: 8082
     targetPort: 8082
