apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  labels:
    app: todos-api
  namespace: parcial2
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: rolfman/todos_api:0.0.1
          ports:
            - containerPort: 8082
          env:
            - name: JWT_SECRET
              value: "PRFT"

---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: parcial2
  labels:
    app: todos-api
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: todos-api