apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: proyecto
  labels:
    app: todos-api
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: todos-api
