apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
  namespace: parcial2
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: rolfman/users_api:0.0.1
          #ports:
           # - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: JWT_SECRET
              value: "PRFT"

---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: parcial2
  labels:
    app: users-api
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: users-api