apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiat-exam
  name: frontend-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: davidfiat24/vuejs:latest
        ports:
        - containerPort: 8080