apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
  namespace: proyecto
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: camilo1909/auth-api:0.1
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_API_PORT
              value: "8000"
            - name: JWT_SECRET
              value: "PRFT"
            - name: USERS_API_ADDRESS
              value: "http://users-api:8083"

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: proyecto
  labels:
    app: auth
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: auth