apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
  namespace: proyecto
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: camilo1909/users-api:0.1
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET
              value: "PRFT"

---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: proyecto
  labels:
    app: users
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: users