#Load balancer service kubernetes
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fiat-exam
spec:
  type: LoadBalancer
  selector:
    app: frontend-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
