apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto
  name: auth
  labels:
   app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
         app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
     containers:
     - name: auth
       image: manymanito/auth-api:0.0.1
       env:
        - name: JWT_SECRET
          value: PRFT
        - name: AUTH_API_PORT
          value: "8000"
        - name: USERS_API_ADDRESS
          value: "http://users:8083"
       ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
 namespace: proyecto
 name: auth
 labels:
  app: auth
spec:
 type: ClusterIP
 selector:
  app: auth
 ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http