apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto
  name: log-message
  labels:
   app: log-message
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
         app: log-message
  template:
    metadata:
      labels:
        app: log-message
    spec:
     containers:
     - name: log-message
       image: manymanito/log-message-processor:0.0.1
       env:
        - name: REDIS_HOST
          value: "127.0.0.1"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log_channel" 
       ports:
        - containerPort: 8081
     - name: redis
       image: redis
       ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
 namespace: proyecto
 name: log-message
 labels:
  app: log-message
spec:
 type: LoadBalancer
 selector:
  app: log-message
 ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: http