apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs
  labels:
   app: logs
  namespace: distribuidosparcial
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
         app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
     containers:
     - name: redis
       image: redis:alpine 
     - name: logs
       image: andres192715/log-message-processor:0.0.2
       env:
        - name: REDIS_HOST
          value: "127.0.0.1"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log_channel"
 
---

#apiVersion: v1
#kind: Service
#metadata:
# name: logs
# namespace: distribuidosparcial
# labels:
#  app: logs
#spec:
# type: LoadBalancer
# ports:
#  - port: 6379
#    targetPort: 6379
#    protocol: TCP
# selector:
#  app: logs   