apiVersion: v1
kind: Service
metadata:
  name: distri-users
spec:
  selector:
   project: exam2
   service: distri
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8083
     name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 2
  template:
    metadata:
      labels:
        app: users
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      replicas: 2
      containers:
      - name: users
        image: raritysponytail/users-img:0.0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: JWT_SECRET
            value: "PRFT" 
          - name: SERVER_PORT
            value: "8083"
        ports:
            - containerPort: 8083
        resources:
          limits:
              memory: 512Mi
              cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"