apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto
  name: users
  labels:
   app: users
spec:
  replicas: 2
  selector:
    matchLabels:
         app: users
  template:
    metadata:
      labels:
        app: users
    spec:
     containers:
     - name: users
       image: manymanito/users-api:0.0.1
       env:
        - name: JWT_SECRET
          value: PRFT
        - name: SERVER_PORT
          value: "8082"
       ports:
        - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
 namespace: proyecto
 name: users
 labels:
  app: users
spec:
 type: ClusterIP
 selector:
  app: users
 ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
    name: http